name: CodeCov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3 # check out this source code
    
    - name: Install OS Packages
      uses: ConorMacBride/install-package@v1
      with:
          apt: libglib2.0-dev # needed for radiacode->bluepy
          
    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Run tests using ${{ matrix.python-version }}
      run: |
        uv sync --all-extras
        env TZ=UTC uv run --frozen pytest --cov=src --cov-report=xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true